SP_enemy_normal_explotion = ["Sprites/Explotions/explotion_1.png", "Sprites/Explotions/explotion_2.png", "Sprites/Explotions/explotion_3.png"]
SP_enemy_normal = ["Sprites/enemy_1.png", "Sprites/enemy_2.png"]
SP_enemy_spaceship = ["Sprites/Score/score_1.png", "Sprites/Score/score_2.png"]
SP_player_bullet = ["Sprites/Explotions/player_bullet_1.png","Sprites/Explotions/player_bullet_2.png"]
SP_NEW_STAGE = ["Sprites/new_stage_1.png","Sprites/null.png"]